[project]
name = "BouvetRadar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=4.0.0",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
