name: Bug Report
description: Create a report to help us improve.
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much information as possible to help us understand and resolve the issue.
  - type: input
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: e.g. "When I click the submit button, nothing happens."
      required: true
  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. "I expected the form to submit and show a success message."
      required: true
  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: e.g. "![screenshot](url)"
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment (e.g., OS, browser version, device).
      placeholder: e.g. "Windows 10, Chrome 89"
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: e.g. "I noticed this issue started happening after I updated my browser."
      required: false