name: Bug Report
description: Create a report to help us improve.
title: "What is the bug?"
labels: ["bug"]
projects: [1]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much information as possible to help us understand and resolve the issue.
  - type: input
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: e.g "When I click the submit button, nothing happens."
      
  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: How can this issue be reproduced?
      
  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. "I expected the form to submit and show a success message."
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is this bug related to?
      options:
        - Frontend
        - Backend
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: e.g. "I noticed this issue started happening after I updated my browser."
      