name: Management Task 
description: Create a management task.
title: "What is the task?"
labels: ["management task"]
projects: "github/1"
assignees: []
body:
  - type: markdown
    attributes:
      value: |      
        Thanks for taking the time to create a task! Please provide as much detail as possible to help us understand and prioritize your request.
  - type: input
    id: task-description
    attributes:
      label: Task Description
      description: A clear and concise description of the task you are suggesting.
      placeholder: e.g. "I need to update the user documentation for the new feature."
  - type: textarea
    id: task-details
    attributes:
      label: Task Details
      description: Additional details about the task.
      placeholder: e.g. "Include any relevant information or context."
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the task here.
      placeholder: e.g. "This task is part of a larger project to improve user onboarding."