name: New Feature
description: Suggest a new feature or enhancement.
title: "What is the new feature?"
labels: ["enhancement"]
projects: "github/1"
assignees: []
body:
  - type: markdown
    attributes:
      value: |      
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand and evaluate your suggestion.
  - type: input
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you are suggesting.
      placeholder: e.g. "I would like to see a dark mode option for the application."
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: What is the initial status for this task?
      options:
        - Backlog
        - In progress
      default: 0  # This makes "Backlog" the default
  - type: input
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature? Please provide specific examples if possible.
      placeholder: e.g. "I often work at night and a dark mode would reduce eye
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to Have
        - Important
        - Critical
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature relate to?
      options:
        - Frontend
        - Backend
        - Documentation
        - Other
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: e.g. "I have seen similar features in other applications like XYZ."